#!/bin/sh
# Fix permissions on the given directory to allow group read/write of
# regular files and execute of directories.
chown -R 1001:0 "$1"
chmod -R 700 "$1"
#find "$1" -type d -exec chmod g+x {} +
